name: Build and deploy Node.js app to Azure Web App - mlaku-mulu-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Apply Prisma Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy

      - name: Build application
        run: npm run build --if-present

      - name: Run tests
        run: npm run test --if-present

      - name: Cleanup and Prepare ZIP
        run: |
          mkdir deploy-package
          cp -R . deploy-package
          rm -rf deploy-package/node_modules
          rm -rf deploy-package/.git
          rm -rf deploy-package/.github
          rm -rf deploy-package/.next
          rm -rf deploy-package/prisma/migrations
          zip -r release.zip deploy-package

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Debug: List files before deployment
        run: ls -la

      - name: Cleanup Old Deployment (Avoid Conflict)
        run: |
          az webapp stop --name mlaku-mulu-backend --resource-group mlaku-rg
          az webapp delete --name mlaku-mulu-backend --resource-group mlaku-rg --keep-empty-app

      - name: Debug Azure CLI
        run: az account show

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mlaku-mulu-backend'
          slot-name: 'Production'
          package: release.zip
